spring:
  application:
    name: Delivery-Management-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_manager_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/drivermanager/
  error:
    include-exception: true
    include-message: always

mapbox:
  api:
    key: pk.eyJ1IjoiYXJ1bmFsdSIsImEiOiJjbTllZ3ZleHUxZWlxMmxzN3hyMmlxaXBjIn0.88xrwVeZkSlah-fUY3_3BA
    enabled: true
