spring:
  application:
    name: Delivery-Management-Service-Microservices-DS
  data:
    mongodb:
      uri: mongodb+srv://arunalubamunusinghe75:Arunalu123@cluster0.n5poqff.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: DriverManager

server:
  port: 8080
  servlet:
    context-path: /api/drivermanager/
  error:
    include-exception: true
    include-message: always

mapbox:
  api:
    key: pk.eyJ1IjoiYXJ1bmFsdSIsImEiOiJjbTllZ3ZleHUxZWlxMmxzN3hyMmlxaXBjIn0.88xrwVeZkSlah-fUY3_3BA
    enabled: true
